export const controlOptions = {
  display: {
    flex: "Flex",
    grid: "Grid",
  },
  padding: {
    base: "Base",
    xsm: "X-Small",
    sm: "Small",
    md: "Medium",
    lg: "Large",
    xl: "X-Large",
    xxl: "Xx-Large",
    none: "None",
  },
  margin: {
    base: "Base",
    xsm: "X-Small",
    sm: "Small",
    md: "Medium",
    lg: "Large",
    xl: "X-Large",
    xxl: "Xx-Large",
    none: "None",
  },
  size: {
    1: "X-Small",
    2: "Small",
    3: "Medium",
    4: "Large",
    5: "X-Large",
    6: "XX-Large",
  },
  gridSizes: {
    1: "X-Small",
    2: "Small",
    3: "Medium",
    4: "Large",
    5: "X-Large",
    6: "XX-Large",
  },
};
